# Generated by Django 5.0.3 on 2024-08-29 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='conversation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='langchain_stream.conversation'),
            preserve_default=False,
        ),
    ]
