# Generated by Django 5.0.3 on 2024-09-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_stream', '0003_ragchainstore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RAGChainStore',
        ),
    ]
