# Generated by Django 5.0.3 on 2024-09-03 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_stream', '0004_delete_ragchainstore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
