# Generated by Django 5.0.3 on 2024-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_stream', '0007_chatmessage_selected_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='selected_model',
        ),
        migrations.AddField(
            model_name='conversation',
            name='selected_model',
            field=models.CharField(default='mixtral-8x7b-32768', max_length=255),
        ),
    ]
