# Generated by Django 5.0.3 on 2024-09-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langchain_stream', '0008_remove_chatmessage_selected_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='selected_model',
        ),
    ]
